=== Sanoy2/XMLLab3/Lab3_task1.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="person">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="surname" type="xs:string" />
                <xs:element name="homeAddres">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="city" type="xs:string" />
                            <xs:element name="zipCode" type="xs:string" />
                            <xs:element name="street" type="xs:string" />
                            <xs:element name="number" type="xs:string" />
                            <xs:element name="country" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="phone" type="xs:integer" />
                <xs:element name="mobile" type="xs:integer" />
                <xs:element name="job" type="xs:string" />
                <xs:element name="birthDate">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="day" type="xs:integer" />
                            <xs:element name="month" type="xs:integer" />
                            <xs:element name="year" type="xs:integer" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

<!-- Author: Krzysztof Tomkow, index number: 218514 -->

=== Sanoy2/XMLLab3/Lab3_task1.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Lab3_task1.xsd">
    <name>John</name>
    <surname>Doe</surname>
    <homeAddres>
        <city>New York</city>
        <zipCode>00-000</zipCode>
        <street>Foo Street</street>
        <number>2</number>
        <country>USA</country>
    </homeAddres>
    <phone>657263819</phone>
    <mobile>739283648</mobile>
    <job>Architect</job>
    <birthDate>
        <day>10</day>
        <month>7</month>
        <year>1976</year>
    </birthDate>
</person> 

<!-- Author: Krzysztof Tomkow, index number: 218514 -->
