=== Sanoy2/XMLLab3/Lab3_task5.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="courses">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="course" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Application programming Java and XML technologies" />
                                        <xs:enumeration value="Information System Analysis" />
                                        <xs:enumeration value="Secure Systems and Networks" />
                                        <xs:enumeration value="Advanced Databases" />
                                        <xs:enumeration value="Multimedia and Computer Visualisation" />
                                        <xs:enumeration value="Softcomputing" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="forms">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="form" minOccurs="1" maxOccurs="5">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="formName">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="Lecture" />
                                                                <xs:enumeration value="Laboratory" />
                                                                <xs:enumeration value="Project" />
                                                                <xs:enumeration value="Execrices" />
                                                                <xs:enumeration value="Seminar" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="hours" type="xs:string" />
                                                    <xs:element name="lecturer" minOccurs="1" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="firstName" type="xs:string" />
                                                                <xs:element name="lastName" type="xs:string" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

<!-- Author: Krzysztof Tomkow, index number: 218514 -->

=== Sanoy2/XMLLab3/Lab3_task5.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<courses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Lab3_task5.xsd">
    <course>
        <name>Application programming Java and XML technologies</name>
        <forms>
            <form>
                <formName>Lecture</formName>
                <hours>
                    30
                </hours>
                <lecturer>
                    <firstName>Tomasz</firstName>
                    <lastName>Walkowiak</lastName>
                </lecturer>
            </form>
            <form>
                <formName>Laboratory</formName>
                <hours>
                    15
                </hours>
                <lecturer>
                    <firstName>Marek</firstName>
                    <lastName>Woda</lastName>
                </lecturer>
            </form>
            <form>
                <formName>Execrices</formName>
                <hours>
                    15
                </hours>
                <lecturer>
                    <firstName>Marek</firstName>
                    <lastName>Woda</lastName>
                </lecturer>
            </form>
        </forms>
    </course>
    <course>
        <name>Information System Analysis</name>
        <forms>
            <form>
                <formName>Lecture</formName>
                <hours>
                    15
                </hours>
                <lecturer>
                    <firstName>Paweł</firstName>
                    <lastName>Głuchowski</lastName>
                </lecturer>
                <lecturer>
                    <firstName>Jan</firstName>
                    <lastName>Magott</lastName>
                </lecturer>
                <lecturer>
                    <firstName>Tomasz</firstName>
                    <lastName>Babczyński</lastName>
                </lecturer>
            </form>
            <form>
                <formName>Laboratory</formName>
                <hours>
                    30
                </hours>
                <lecturer>
                    <firstName>Paweł</firstName>
                    <lastName>Głuchowski</lastName>
                </lecturer>
                <lecturer>
                    <firstName>Jan</firstName>
                    <lastName>Magott</lastName>
                </lecturer>
                <lecturer>
                    <firstName>Tomasz</firstName>
                    <lastName>Babczyński</lastName>
                </lecturer>
            </form>
        </forms>
    </course>
    <course>
        <name>Secure Systems and Networks</name>
        <forms>
            <form>
                <formName>Lecture</formName>
                <hours>
                    30
                </hours>
                <lecturer>
                    <firstName>Tomasz</firstName>
                    <lastName>Surmacz</lastName>
                </lecturer>
            </form>
            <form>
                <formName>Laboratory</formName>
                <hours>
                    15
                </hours>
                <lecturer>
                    <firstName>Tomasz</firstName>
                    <lastName>Surmacz</lastName>
                </lecturer>
            </form>
        </forms>
    </course>
    <course>
        <name>Advanced Databases</name>
        <forms>
            <form>
                <formName>Lecture</formName>
                <hours>
                    15
                </hours>
                <lecturer>
                    <firstName>Maciej</firstName>
                    <lastName>Nikodem</lastName>
                </lecturer>
            </form>
            <form>
                <formName>Laboratory</formName>
                <hours>
                    30
                </hours>
                <lecturer>
                    <firstName>Maciej</firstName>
                    <lastName>Nikodem</lastName>
                </lecturer>
            </form>
        </forms>
    </course>
    <course>
        <name>Multimedia and Computer Visualisation</name>
        <forms>
            <form>
                <formName>Lecture</formName>
                <hours>
                    30
                </hours>
                <lecturer>
                    <firstName>Marek</firstName>
                    <lastName>Woda</lastName>
                </lecturer>
            </form>
            <form>
                <formName>Project</formName>
                <hours>
                    15
                </hours>
                <lecturer>
                    <firstName>Christopher</firstName>
                    <lastName>Chiu</lastName>
                </lecturer>
            </form>
        </forms>
    </course>
    <course>
        <name>Softcomputing</name>
        <forms>
            <form>
                <formName>Lecture</formName>
                <hours>
                    30
                </hours>
                <lecturer>
                    <firstName>Jacek</firstName>
                    <lastName>Mazurkiewicz</lastName>
                </lecturer>
            </form>
            <form>
                <formName>Project</formName>
                <hours>
                    15
                </hours>
                <lecturer>
                    <firstName>Christopher</firstName>
                    <lastName>Chiu</lastName>
                </lecturer>
            </form>
        </forms>
    </course>
</courses> 

<!-- Author: Krzysztof Tomkow, index number: 218514 -->
